global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 1. Frontend
  - job_name: 'feedback-frontend'
    metrics_path: '/metrics'
    authorization:
        type: Bearer
        credentials: 'CcKuuiQHEAJdRVXQKZyi5ZIx9aazgFaZ89M8hbwsQ7l949rSKrmAUCC3MviUCeA'    
    static_configs:
      - targets: ['feedback-board:3000']

  # 2. Docker
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['Feedback-Board-Cadvisor:9109']

  # 3. Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  # 4. Node-Exporter
  - job_name: 'node-exporter'
      static_configs:
        - targets: ['node-exporter:9100']
