global:
  scrape_interval: 15s

scrape_configs:
  # Frontend
  - job_name: 'feedback-frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['Feedback-Board-Frontend:3000']

  # PocketBase
  - job_name: 'feedback-pocketbase'
    static_configs:
      - targets: ['Feedback-Board-Cadvisor:9109']
    params:
      container: ['Feedback-Board-Pocketbase']
